### ISSUE TITLE
Conflict with Vue 2.1.7+

### ISSUE THREAD

**Issue by kharysharpe** [lakb248/vue-pull-refresh#1]
Hey @lakb248,

I would like to use your vue-pull-refresh component but I think the latest version of Vue has created some conflicts.

Release reads:
**If you are the author of a plugin/component that ships a pre-compiled dist file:**

It is recommended to re-compile the dist file using the latest versions of vue-template-compiler and vue-template-es2015-compiler. The new generated code is backwards-compatible, but code generated by older versions of the compilers may not work properly with the latest runtime.

Code generation changes that affect compatibility are very rare and we will avoid introducing similar changes in future patch releases.

See: 
https://github.com/vuejs/vue/releases/tag/v2.1.7

As per above please can you update, recompile/rebuild and publish to npm?

**Comment by lakb248** [comment]
Hi, I hava rebuild the dist file and publish to npm, thank you.

**Comment by kharysharpe** [comment]
THANK YOU! Works :)
