### ISSUE TITLE
Labels ignored if set to ""

### ISSUE THREAD

**Issue by jezmck** [lakb248/vue-pull-refresh#11]
To allow for an empty Loading label for instance, we'll need some different code to check for labels' values.

https://github.com/lakb248/vue-pull-refresh/blob/master/src/vue-pull-refresh.vue#L56-L59

**Comment by lakb248** [comment]
OK, If you are in hurry，you can make a pull request, or I will fix it in 24 hours

**Comment by jezmck** [comment]
I have a CSS workaround for now, thank you.
