### ISSUE TITLE
How do you set the message/labels in vue-pull-refresh?

### ISSUE THREAD

**Issue by kharysharpe** [lakb248/vue-pull-refresh#2]
How do you override the LABELS?

Also is it possible to change it to be set via a property instead

Like
```
<vue-pull-refresh pullText="Pull to Refresh" releaseText="Release to Refresh"  loadingText="Loading..." errorText="Data Exception">
   <content/>
</vue-pull-refresh>
```
Any thing not set uses defaults.

What do you think?

**Comment by lakb248** [comment]
Good idea! I will update the component later today

**Comment by lakb248** [comment]
Hi, I have updated the package to customize LABELS when pull down. You can update the package to use.

**Comment by kharysharpe** [comment]
Thank you. Will check it out shortly.
